
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
cds:
  security:
    mock:
      users:
        admin:
          password: admin
          roles:
          - admin
        user:
          password: user
  data-source:
    auto-config:
      enabled: false
